### ISSUE TITLE
Mouse Limit and Game Crash

### ISSUE THREAD

**Issue by TransGordon** [malortie/uncompleted-compilable-hl-opfor#2]
The following two issues seem to occur only in your source code. After building the dll and cl_dll through Visual Studio 2017, I started my mod; and here is what happened:

1.) You can only move the mouse around within 90 degrees per direction.
2.) In the intro level "Incoming", the first map from Half-Life: Opposing Force, the game seems to crash just before there is ever an explosion from the troop carrier destroyed by one of those giant flying sting rays.

Just to clarify, I did not edit nor alter your source code when this happened.

**Comment by SamVanheer** [comment]
Your first problem is probably caused by the raw mouse input setting. Go to Options->Mouse->Raw mouse input and toggle it. That should solve the input issue.

Your second problem happens because env_spritetrain isn't fully implemented so it never triggers the fire on pass targets for its path_corner entities, which are supposed to killtarget the alien beam effects. As a result the beam tries to use one of the alien ship entities, which is killtargeted when the ship hits a path_track of its own so it tries to pass a reference to the origin of that ship to the engine, which then causes a crash due to dereferencing freed memory.

To fix this env_spritetrain needs to be fully implemented. It should be relatively easy to do, inherit from func_train and internally create an env_sprite using MOVETYPE_FOLLOW to attach it to the train.

**Comment by malortie** [comment]
@SamVanheer 

I can confirm that the points mentioned by @SamVanheer are correct.

Thank you.

**Comment by malortie** [comment]
@TransGordon 

I was referred by @SamVanheer  to this thread: https://twhl.info/thread/view/19665?page=last
@TransGordon , please correct me if I am wrong, but I do believe that you are the creator of this thread.

In this thread, you did mention that the Opposing Force sub title was not appearing in the game.
Back then, this was not implement it yet, but I just pushed a few changes that make the Opposing Force title display correctly, as you wished. In addition to this, I did remove an assertion that could occur when attempting to use the displacer when no earth and xen target were available.

For the list of changes, please refer to this commit: https://github.com/malortie/uncompleted-compilable-hl-opfor/commit/282cd53793d3ea03082dffe830b0c2edae8db727

**Comment by TransGordon** [comment]
> Your first problem is probably caused by the raw mouse input setting. Go to Options->Mouse->Raw mouse input and toggle it. That should solve the input issue.
> 
> Your second problem happens because env_spritetrain isn't fully implemented so it never triggers the fire on pass targets for its path_corner entities, which are supposed to killtarget the alien beam effects. As a result the beam tries to use one of the alien ship entities, which is killtargeted when the ship hits a path_track of its own so it tries to pass a reference to the origin of that ship to the engine, which then causes a crash due to dereferencing freed memory.
> 
> To fix this env_spritetrain needs to be fully implemented. It should be relatively easy to do, inherit from func_train and internally create an env_sprite using MOVETYPE_FOLLOW to attach it to the train.

The first problem is not the raw mouse input. I know this, because it's already on. Not even turning it off makes any difference. The mouse just keeps hitting corners.

**Comment by TransGordon** [comment]
> The class `CSpriteTrain` is in `effects.cpp`. Unfortunately there is no easy way to explain how to fix it, if you don't have the programming skills to work with C++ you'll have a hard time understanding anything it.
> 
> You'll probably have to fix/implement more entities after this one so if you don't already know how to do GoldSource modding this will be very hard. If you're up for that, i'd suggest reading tutorials and getting used to the SDK before trying to do that.

Hold on. First you said easy, and now you said hard? I'm confused. Also, I don't know which tutorial to look up in particular. There are too many of them, yet not a whole lot of them focus on how to fix this kind of problem. The other thing, I looked at other HL source code projects; and they except this one don't have the class 'CSpriteTrain'. And how many entities? Which ones in particular?

**Comment by SamVanheer** [comment]
If you know C++ then it's relatively easy, but since you seemingly don't know it will be much harder to explain.

GoldSource is a hard codebase to learn to use, even for someone with experience in C++. That's why it's best to get the hang of programming in C++ first before starting with the SDK.

`CSpriteTrain` was added to Opposing Force only. As far as i know only Sven Co-op implements it, but it's basically just a combination of a `func_train` and an `env_sprite` to make up for the lack of entity parenting like Source has. There probably aren't any mods with source code available that implement this.

As far as other entities go, i don't know how much of Opposing Force @malortie managed to implement. As the readme states it's incomplete.

For tutorials, a good C++ tutorial can be found here: http://www.cplusplus.com/doc/tutorial/

Note that the SDK was written in C++98, so you'll have to get used to writing code the old way. You won't be able to rely on some newer features without major rewrites.

For help with programming with the SDK i'd suggest asking on TWHL since i know some people have been getting into it and maybe writing tutorials.

Otherwise your best bet will be waiting for somebody else to do what you're trying to do. Unless Valve decides to open source the games there isn't any other option available for you.

**Comment by TransGordon** [comment]
> If you know C++ then it's relatively easy, but since you seemingly don't know it will be much harder to explain.
> 
> GoldSource is a hard codebase to learn to use, even for someone with experience in C++. That's why it's best to get the hang of programming in C++ first before starting with the SDK.
> 
> `CSpriteTrain` was added to Opposing Force only. As far as i know only Sven Co-op implements it, but it's basically just a combination of a `func_train` and an `env_sprite` to make up for the lack of entity parenting like Source has. There probably aren't any mods with source code available that implement this.
> 
> As far as other entities go, i don't know how much of Opposing Force @malortie managed to implement. As the readme states it's incomplete.
> 
> For tutorials, a good C++ tutorial can be found here: http://www.cplusplus.com/doc/tutorial/
> 
> Note that the SDK was written in C++98, so you'll have to get used to writing code the old way. You won't be able to rely on some newer features without major rewrites.
> 
> For help with programming with the SDK i'd suggest asking on TWHL since i know some people have been getting into it and maybe writing tutorials.
> 
> Otherwise your best bet will be waiting for somebody else to do what you're trying to do. Unless Valve decides to open source the games there isn't any other option available for you.

Look, make no mistake. I would love to do this myself, but I don't have the time nor the capacity. I'll step down and let someone else take a look at it.

Just one last thing I do want to point out. In the intro of "Boot Camp", you're able to move your character around while the drill instructor is still giving everyone his morning speech. His voice also gets cut off when you do this.

I'm back to this SDK:
https://github.com/malortie/halflife/tree/branch-malortie-op4

Even with all of the fixes from the commits implemented, the exact same problems seem to exist in there.

That is all. I'll check back when there's an update.
