### ISSUE TITLE
why porting to vs2017 this code |well compiling| with vs 2010 

### ISSUE THREAD

**Issue by sixcentgeorge** [malortie/uncompleted-compilable-hl-opfor#6]
i started to become a c++ learner&programmer , my friend..
after analyse of the project of solokiller for opposing force ..  : https://github.com/Solokiller/halflife-op4/issues/15

what an asshole is this..but on the other side.. that explains a lot about bugs i found in latest svencoop where the solokiller-angel-script is the "master-piece"

i tried to compile your code : https://github.com/malortie/halflife
with vc2010 .. that i had installed long ago...and then tried to do it with this project.. but the compilator fails at the beginning.. only for a question of "version" .. it says xp 141.. that should be more a question of cpu than pure coding.. as you reused the halflife project as a base..

can you create a new project file so this project will be compilable with vc 2010 ..?

i want to try to mix your project with the one made be your others good friends from xash3d / hlfx.ru   by modb and svencoop :  https://github.com/Hammermaps-DEV/SOHL-V1.9-Opposing-Force-Edition  ...

i found a link having the missing "big file" 

https://drive.google.com/uc?id=1smLdf_iyg0iZ_p4-v9HCCZJj5vgcSyEQ&export=download

it is the mod folder .. it has some interresting maps : i played one monsterdemo.. where the vortigaunt was the best shooter..of all monsters..
the models are "fixed" but unable to play any anim of the opposing force mod..  [ another real solokiller+snipper+viking svencoops  "touches" ]

i joke but i was waiting for something else.. spirit of hl .. was another famous project around hl that made a lot of noise about Quality.. like black-mesa...   years later it is very interresting to see the real results ...  very very bad..

so i wait something compilable with vc2010 of this project please..

**Comment by malortie** [comment]
@sixcentgeorge 

> i tried to compile your code : https://github.com/malortie/halflife
with vc2010 .. that i had installed long ago...and then tried to do it with this project..
but the compilator fails at the beginning.. only for a question of "version" .. it says xp 141..

Based on the description of your problem, the cause is likely that you do not have the   Visual Studio 2017 C++ redistribuable installed. To be able to build using the 141 xp toolset, you need to install the Visual Studio 2017 C++ redistribuable. [I found a page](https://support.microsoft.com/en-ca/help/2977003/the-latest-supported-visual-c-downloads) where you can possibly install it, but I would recommend that you directly [install Visual Studio 2019](https://visualstudio.microsoft.com/downloads/), as it can migrate 2010 projects to use the most recent toolset, which is 142. You can download Visual Studio 2017 or 2019 community edition.

> can you create a new project file so this project will be compilable with vc 2010 ..?

I do not have Visual Studio 2010 installed and I will not download it. Is it possible to ask why it would be preferable to remain on VS 2010? Instead, You could get the community edition of Visual Studio 2017 or 2019. It's free.

Did you check [this branch](https://github.com/malortie/halflife/tree/branch-malortie-vs-2017RC)?

It contains a [fully setup solution file](https://github.com/malortie/halflife/tree/branch-malortie-vs-2017RC/projects/vs2017RC) "projects.sln" to be used in VS 2017.

I compiled the branch with Visual Studio 2019 and it works without error. You could use this branch in conjunction with "uncompleted-compilable-hl-opfor". This would allow you to make the changes you want and develop on a more recent and more modern version of Visual Studio.

If you wish to try and build the source code of the current repository using Visual Studio 2010 and without installing the Visual C++ 141 xp redistribuable, there could be a way but this will require a few tweaks. Please try and follow these instructions, but be aware that it is impossible for me to verify if it will work:

1. Download a fresh copy of this repository.
2. Go to folder "projects" and open the file "gearboxdll.vcxproj" with a text editor. e.g. Notepad/Notepad++
3. Find the following line (around line 2).

```xml
<Project DefaultTargets="Build" ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
```

and replace `15.0` with `4.0`. You should have:
```xml
<Project DefaultTargets="Build" ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
```

4. Remove every instance of the following (around line 23 and 30)
```xml
<PlatformToolset>v142</PlatformToolset>
```

5. Redo steps 3 and 4 with gearbox_cdll.vcxproj.

6. Open Visual Studio 2010 and create an empty/blank solution file. This will create an .sln with no projects. In the new solution, add the projects gearboxdll.vcxproj and gearbox_cdll.vcxproj

7. In Visual Studio, right click on gearbox.vcxproj and go to "Properties".
8. Click on the tab "General" and look for the property "Platform toolset". Ensure that the current value in "Plaform toolset" is "v100". 
   
9. Redo steps 7 and 8 with gearbox_cdll.vcxproj.

10. In Visual Studio, save your new solution, right click at the root of your solution and click "Build all".

It should work in theory, as the file structure of .vcxproj is not very different among versions apart from the specified ToolsVersion "15.0" that we changed to "4.0" earlier. This does not imply that you will not get compile warnings/errors. Please let me know if it works.

**Comment by sixcentgeorge** [comment]
i start to understand .. why you are "so much" suffering.. .. while for me life is : 

https://www.youtube.com/watch?v=pjJ2w1FX_Wg
[nice song and very young singer.. no ? her dancers are cute too.. ]

i followed your link and it says to download sp1 for vc2010.. without a word about this xp_141 ..i searched a little more : 

Visual Studio 2019 et ultérieur n’inclut pas la prise en charge de la création de code pour Windows XP à l’aide de l’ensemble d’outils v142. La prise en charge du développement Windows XP à l’aide de l’ensemble d’outils v141 fourni dans Visual Studio 2017 est disponible en tant que composant facultatif dans Visual Studio Installer.

in fact vc 17 or above are not very compatible with the hlsdk ..
the difference is like win9x and win nt ... yes that is only M$  bullshitting ..i mean his code is so bad that it needs all the cpu and some registers are no longer available.. windows can only support to "give" half of the cpu" to programs and keep the rest for itself..
even a cpu with win2010 at 5 Ghz is not as fast as an old pentium 2 300Mhz with win 98 if you use others memory managers than the M$ himem.sys ...some like qemm386.sys with 4dos ..Grrr <3 <3

the best is to use the vc2010 or the previous..
mostly because it has a lot of patch removing a lot of bugs.. something that will never have the xp_141...
saying it is freee .. is like saying windows 10 is good....
M$ had to do like Linux and recently Apple did : to give for free their OS
they continue to earn a lot with the "signature" of drivers..and others products..plus when it is a "new" computer you have to pay the licence... [ at least compagnies do it "honestly" : because their customers pay...]

for the v141 trick .. i will try it .. i was not sure about finding it..with the GUIDS that makes another "king size black hole" inside windows where i do not like to ROAM.. ;']
if i look at the sln i have it says :

Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio 15
VisualStudioVersion = 15.0.26430.13
MinimumVisualStudioVersion = 10.0.40219.1
Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "gearbox_cdll", "gearbox_cdll.vcxproj", "{DC1DD765-CFEB-47DA-A2EA-9F1E20A24272}"
	

10.0.40219.1 is the matching number i have in the about box of vc2010 sp1

i ll test that solution after posting ..
what is your opinion on the the spirit of half life v19 special opposing force ?
do you think some part of it are useable with your work ?

that could be good to finish by making it : the dll for opposing force.. after twenty years ..

i also read https://github.com/jlecorre/hlinvasion files..
this project use files made for vs 6 .. so there are a lot of little errors and no dlls..
the mod was mode by french and had few good tricks like a 2 D battle with a tank.. plus it has a garg arm as weapon..and few others nice models..
http://hlinvasion.free.fr/


i can not understand how it is possible you have so "impossible" to recreate the dlls with the monsters.. moreover because you are all great friends by moddb and svencoop ..  
these two suckers of sniper & sven-bling-bling had never gave you any files ?
in my mind these both are like : wanting to play coop but keep all he can for himself ..
like with the famous they hunger : on which they have no more rights than anyone else... not even the one to forbid doing it for playing with svencoop ..
they wrote they have the maps from sir Manke..  i think he gave them to them for it to be distributed across a large public...for free.. not for two suckers to try to earn money using them at their profit.. like the famous black-mesa project and its defunct forum..

by the way they are soon "gone with the wind of time"
so i ll try your tricks.. try to see if spirit v19 or invasion can give something to the mod..opposing force..
that could be cool if can create a dll able to play svencoop with xash3d.. or all others mods made for opposing force ..

**Comment by malortie** [comment]
@sixcentgeorge 

> what is your opinion on the the spirit of half life v19 special opposing force ?

I remember browsing this repository a while ago (maybe 1-2 year ago?). I remember I had a quick look at several files, but I never compiled the source code so I never experienced it, therefore I am afraid I have no constructive opinion on it.

> do you think some part of it are useable with your work ?

To be able to know if there are parts of half life v19 special opposing force repo you could reuse with my code, you will need to study the source code on the repository or you will need to contact the author and ask him about the current status of the repo, and how much is complete and useable. As for the "uncompleted-compilable-hl-opfor" code, I do not recommend that you use it. I stated the issues with the currrent source code [here - paragraph before bug list](https://github.com/malortie/uncompleted-compilable-hl-opfor/issues/5#issuecomment-583942871), but the choice is up to you.

> i can not understand how it is possible you have so "impossible" to recreate the dlls with the monsters..

[In this post - third paragraph](https://github.com/malortie/uncompleted-compilable-hl-opfor/issues/5#issuecomment-583942871), I explained that unless you have the source code of the original mod, you will need to reimplement them as if you would have been the programmer of the original mod. In the case of HL invasion, the source code is already available so it would not be difficult to do so (basically just adding a few new files and comparing the changes between your mod's files and theirs). In the case of Sweet HL, to my knowledge, the source code has never been publicly released. If you want to use monsters and weapons, from SweetHL, you will have to either contact to the original mod creator and ask for the original source code or recode them from scratch and ensure they behave the same as in the original mod. Sometimes, "dll recreation" from scratch may is simple, but other times it may be difficult, and in the case of SweetHL, taking the example of the Kingpin, the set of attacks consist of particle effects, telekinesis powers, player knock-back (so far I have not been able to identify others). The difficulty here in this case would be to match the correct impulse for telekinesis powers and player knock-back, match the correct position, velocity, speed, color, size of every particle effect produced by the Kingpin. In addition, it's important to measure the difficulty to ensure the challenge between the player and Kingpin has almost, or approximately, the same difficulty as in the original mod. 

An example of a simple "dll recreation" would be They Hunger since most of the monsters are zombies that simply reuse the HL's zombie AI. The new weapons in They Hunger are simple to reproduce e.g. The tfc spanner (reuse the crowbar's code), shovel (reuse the crowbar's code).

**Comment by sixcentgeorge** [comment]
you are right on most points.. but with a game that has a sdk of few Mo .. making "existing" models " with "existing sprite"  looking nearly like in the original should not be so hard..
[gearbox_cdll.log](https://github.com/malortie/uncompleted-compilable-hl-opfor/files/4210925/gearbox_cdll.log)
[gearboxdll.log](https://github.com/malortie/uncompleted-compilable-hl-opfor/files/4210926/gearboxdll.log)

i uploaded the log files.. the final dll are not made , compilation stops after 8 warnings and 11 errors..
i feel i will check files from both projects : hl that compiles and opfor that does not..

the way it turns to get this "easy jobs" "made well" reminds me few things about the famous "best in world" university of the usa... where the "young children" aka the students : are paying their teachers .. by now the cost of university is so high that they are nearly unable to pay their debts when working..  the big question is about the quality of what they think they have bought ...and so of these famous teachers...  that looks super low...in fact.. and not worth the big trouble and all the supplemental hours they do..
do you know some forum in japan or south korea where i will be able to ask for help..

**Comment by sixcentgeorge** [comment]
good news : i removed the 4 warnings...
there is a little error in the code : the "int" is missing..
i made screen captures
![first_bug_found](https://user-images.githubusercontent.com/7721742/74613546-a43c5c80-510f-11ea-8e4a-2297d6c51338.JPG)

![4_warnings_removed](https://user-images.githubusercontent.com/7721742/74613561-cb932980-510f-11ea-8209-30d431f9e6ca.JPG)

 so you should find it quick ,,it s nearly midnight ..so i ll keep the errors removing for tomorrow .. ;']
have a nice sunday

**Comment by malortie** [comment]
@sixcentgeorge 

You are almost at it.

> there is a little error in the code : the "int" is missing..

The `int` is not missing. It is declared at line 3385. See this [page](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4258?view=vs-2019) for an explanation about the warning. It says that there is a variable in the for loop with the same name as a variable in the outer scope. More precisely, the outer scope encloses the for loop. It also says that the definition of the "i". In this case, the compiler ignores the for loop definition and uses the variable "i" from the outerscope, which is the "i" declared at line 3385. 

-----

Starting with the error in geneworm.cpp (gearboxdll.log)

Please read about the error [here](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2470?view=vs-2019).

```cpp
const char* CGeneWorm::pHitVolumes[]
{
	"GeneWormRightSlash",
	"GeneWormCenterSlash",
	"GeneWormLeftSlash",
};
```

You get this error likely because of C++ language standard. It compiles without error on C++14 or higher. I would need to test it by setting the language standard, but I cannot do this on VS 2019. The lowest language standard I can set is C++14. Try to add an ` = ` after the ` CGeneWorm::pHitVolumes[] `. You should now have :

```cpp
const char* CGeneWorm::pHitVolumes[] =
{
	"GeneWormRightSlash",
	"GeneWormCenterSlash",
	"GeneWormLeftSlash",
};
```

Tomorrow, I will read the remaining logs and provide you the solutions, progressively. 

-----

> i started to become a c++ learner&programmer

Because you wish to learn c++, I recommend that you try to understand and fix the errors by yourself.

**Comment by sixcentgeorge** [comment]
The int is not missing. It is declared at line 3385.

the only thing i see .. is that the warning does not talk about the "int missing" .. M$ is not so clever and its tools : not so good... to not say : very bad..
i mean like with solokiller model viewer based on hlmv... it can compile code that is having big flaw like a loop that sucks and put one core at full load .. i would not say it is not "like a virus" this kind of error.. but M$ does not hunt this kind of errors or these "ghosts networks" burning electricity for free..   
je veux parler des fameux "reseaux" d ordinateurs pirates par des hackers qui servent a attaquer les reseaux "mal proteges" et pas mis a jour utilisant de vieux windows... l entreprise M$ et les administrations de keufs dans leur immense generoysitee$  interviennent attrapent les voleurs et refermes les failles en patchant les pc ..... a l insu de leur plein gre et sans en parler aux proprietaires...
never heard of this ? lol lol lol

i edited the file geneworm ..i added the = but i also moved the * : like it is above .. *CGeneworm
the elements below are elements in the map where you have to fight it at end of opposing force..

so now there is one DLL that is made : opfor.dll
with a new warning about its names conflicting with hl.dll....  may be you can explain ?

![bug_geneworm_solved](https://user-images.githubusercontent.com/7721742/74629061-a5917780-5157-11ea-8809-68a2ee41abd8.JPG)


"  i started to become a c++ learner&programmer

Because you wish to learn c++, I recommend that you try to understand and fix the errors by yourself.  "

i wonder who should be learning. before saying he is a programmer.. !!!
by now sixcentgeorge : dll 1 ... all others "pro" : 0

i think that like with those friends from hlfx.ru.. that are not here correcting me.. nor solokiller or sniper or vie-bling-vling the sven of svencoop .. i wrote something about it not so long ago :

You get this error likely because of C++ language standard. It compiles without error on C++14 or higher. I would need to test it by setting the language standard to your current language standard (possibly C++03), but I cannot do this on VS 2019. The lowest language standard I can set is C++14. Try to add an = after the CGeneWorm::pHitVolumes[]. You should now have :

with the "latest M$" Visual studio : it is impossible to have a working dll.. even if it is able to produce a file ..  you have to use vc 2010 sp1 or below
c est une histoire de bon sens et de savoir prendre du recul...
corriger les petites erreurs humaines , c est pas si difficile..pour un oeil "neuf" [ enfin presque... ]
en tout cas jc une dll : marc antoine : zero...
le match reprend ;']

**Comment by malortie** [comment]
@sixcentgeorge 

> so now there is one DLL that is made : opfor.dll
with a new warning about its names conflicting with hl.dll.... may be you can explain ?

In the directory "SourceCode/dlls", open the file named "hl.def" with a text editor. e.g. Notepad/Notepad++ and replace the first line `LIBRARY hl` with `LIBRARY opfor`.

**Comment by malortie** [comment]
@sixcentgeorge 

On line

**Comment by malortie** [comment]
Apologies, I accidently closed the issue. Reopened.

**Comment by malortie** [comment]
@sixcentgeorge 

In regards to this error: `in_camera.cpp(102): error C2589: '(' : illegal token on right side of '::'`

In camera.cpp, go to line 102. You should see the following line:
```cpp
if( ::fabs( cur - goal ) > 180.0 )
```

Replace this line with:

```cpp
if( ::fabsf( cur - goal ) > 180.0f )
```

------

In regards to this error: `in_camera.cpp(386): error C2589: '(' : illegal token on right side of '::'`

In camera.cpp, go to line 386. You should see the following line:

```cpp
if( ::fabs( camAngles[ 2 ] - cam_idealdist->value ) < 2.0 )
```

Replace this line with:

```cpp
if( ::fabsf( camAngles[ 2 ] - cam_idealdist->value ) < 2.0f )
```

**Comment by malortie** [comment]
@sixcentgeorge 

In regards to this error: `inputw32.cpp(911): error C2589: '(' : illegal token on right side of '::'`

In inputw32.cpp, go to line 911. You should see the following line:

```cpp
fTemp = 300.0 * pow(::fabs(fAxisValue) / 800.0, 1.3);
```

Replace this line with:

```cpp
fTemp = 300.0f * powf(::fabsf(fAxisValue) / 800.0f, 1.3f);
```

**Comment by sixcentgeorge** [comment]
i wonder if i ll say one day : "M$ kiiled MY Friend Marc..."
i made the second dll and not using your method..
i was testing the two dlls with my first mod : opposing life2life ..with its training that starts like the visitors.. followed by blue-shift train and finally the one of hl.. i have been to the hev room without any bug or crash.. so these dlls i made looks well functioning..
[ i hope you will correct the title and add my name in the credit.. next to your.. of course : fifty-fifty like say children .. ]

i add few scrennshoot showing editions i did plus the zip having the two dlls in debug mode

![bug_zone_joy](https://user-images.githubusercontent.com/7721742/74660284-1fe0ec80-5196-11ea-9cb5-b031ed550b8d.JPG)

may be the code can be removed because the joystick no longer exist ?

![joy_ok](https://user-images.githubusercontent.com/7721742/74660302-2c654500-5196-11ea-96f8-76bad6c25850.JPG)

![camera_bug](https://user-images.githubusercontent.com/7721742/74660396-59b1f300-5196-11ea-8d0e-cd38eef6f9fc.JPG)

![camera_nobug](https://user-images.githubusercontent.com/7721742/74660425-65051e80-5196-11ea-9ebb-5737249d6fa2.JPG)

![camera2_bug0](https://user-images.githubusercontent.com/7721742/74660439-6e8e8680-5196-11ea-9e5a-160a0a193689.JPG)


here are the files ,, i am very proud and happy we made them ..
that will make a lot of youngsters.. having their fun ..

[gearboxdlls_gitub_debug.zip](https://github.com/malortie/uncompleted-compilable-hl-opfor/files/4214141/gearboxdlls_gitub_debug.zip)

now we can start adding things or modifying it ..and test it of course..
have a nice day my friend .. 
jc 2 ma 0 ;']

**Comment by malortie** [comment]
@sixcentgeorge 

> i made the second dll and not using your method..

You have made the right decision when you decided to learn c++. I believe you begin to see the advantages of becoming autonomous in the development of your mod and not having to rely on others to write the code for you.

> may be the code can be removed because the joystick no longer exist ?

Before attempting to remove it, you will need to ask players if they still possess and use joysticks for HL. Create a survey for your users.

For my part, I do not have a joystick and therefore the removal of this functionality would not impact my experience in the mod.

> [ i hope you will correct the title and add my name in the credit..
.. i did plus the zip having the two dlls in debug mode

I never planned to integrate these changes to make the source code compilable under Visual Studio 2010 to the current repository. From my point of view, I do not believe it is worth the effort and the time to implement support for Visual Studio 2010.

If you wish to add VS2010 support for "uncompleted-compilable-hl-opfor", you could fork the current repository and add the new VS2010 .vcxproj but be aware that the changes you made in the source files to make the second DLL compilable under VS2010 could break the builds under Visual Studio 2017 and higher. You will need to install Visual Studio 2017 or higher to verify this. If you plan to do this, please make sure to read **Final note** before doing so.

----

**Final note**

From all the discussions that we had and looking at the state of the current source code, along with the fact that it contains a lot of bugs (more than what I remembered about it), I believe you are right about one thing - it brings no value at all, especially if it does not work for the most part. So I have been thinking lately to delete the current repository. I will however give myself some time to think about it.

----

I wish you all the success in the continuation of your mod.

**Comment by sixcentgeorge** [comment]
the Joystick support was "dropped" by M$ with Xp and the xb0x360 pad...
i think this little part of code made for a specific model is very old so may be removing it or adapting it to the xpad360 can be a good idea..
do not you have one ? i do.. beside i prefer playing with mouse and keyboard..
about the support or not of vc2010 : you have no choice.. 
c est vc 2010 ou tu vas planter les choux ...je veux dire : ton fameux vc2017 et son " xp_2 sans 41 "...ou " sans cas-rente deux "  [ ca sonne pareil en franci que 141 ou 142.. ] sont incapable de compiler ce code..correctement...
donc no choice... i understand this is very hard for you to face "the HUNGER stealer of SVEN BLING BLING" yo aka me .. and owe him the success of this so famous code to compile.. more other after i worked less than few days..
ca troue le cul... mais cest bien ce que je desire " trouer le cul de ces nullards de snippeuse , moddb et autres faignaces du forum svencoop ou hlfx.ru... toutes les verites ne sont pas bonnes a dire.. parait il..  mais avec des loufiats comme ca : une grosse beigne en pleine poire au bon moment : quand ca part "de travers" "a cause des hormones" peut remetre beaucoup de choses en place et eviter des ennuis futur plus grands... 
fifty fifty et 2-0 mon tres cher Marc Antoine..  je te laisse creer un nouveau "hub" avec nous les deux en moderation.... pour le chier sln : j ai pas eu a le refaire.. j ai seulement enlever les references a "xp_141" pour que vc sp1 marche..  [ essaye de voir si y a pas un torrent .. avec la fibre ca devient assez voir tres rapide de telecharger .. de tres gros fichier.. meme en adsl ou satellite ] [ bien sur met offline le "anti virus" qui surveille plus pour flinguer ces fichiers la que pour les virus.. qui ne sont plus tres nombreux.. a par pour voler du ble .. mais c est plus les emails-spams-botnets.. que les virus qui mettent complement off les pc .. j en utilise deux quand meme antivirus..M$ et Avira sur la machine internet .. avec un firewall hardware... j avais achete un firewall qui fait aussi antivirus.. mais ca n a jamais detecte un virus..  par contre le tarif annuel est sale et toute mise a jour manuelle de l antivirus ou les fichiers de definition est IMPOSSIBLE ...  zyxxel est pas pres de me revoir comme client..  avec trois click de souris je telecharge un bartpe ou live linux antivirus qui recupere des fichiers antivirus tout recent.. leur machine a 500 euro "non" ... c est du "vrai sven bling bling" ce machin..  je cherche des fois si y a pas de mise a jour de firmware [ fait par d autre que zyxxel bien sur.. ] comme pour certain routeurs .. dlink.. certains font des supers firmwares et pourtant chez dlink asie ou russie : ils sont plutot tres bon..
donc j attend la nouvelle "hub" mon tres cher ami franci Marc Antoine..
si tu veux on fera une revanche en patins a glace et rondelle l hiver prochain au canada... les poches pleines d oseilles..de l argent de mon mod hell-life ...
tu fais la hub pour opposing-force vc2010 et on fera une autre branche pour le mod..
je suis tout a fait d accord pour que cela soit public ..et aussi que l on se fasse un peu de fric.. les gens les transpirent leurs dollars.. et preferent en donner a des gens sympas qui bossent bien plutot qu aux escrocs et aux impots..

**Comment by malortie** [comment]
@sixcentgeorge 

> je te laisse creer un nouveau "hub" avec nous les deux en moderation.... 
> ...
> tu fais la hub pour opposing-force vc2010 et on fera une autre
> branche pour le **mod**..
>
> donc j attend la nouvelle "hub" ...

Ce que vous me demandez appartient au "développement" de votre mod et je vous ai déjà expliqué que je veux pas travailler sur votre mod.

> can you create a new project file so this project will be compilable with vc 2010 ..?
> ...
> so i wait something compilable with vc2010 of this project please..

Tel que convenu, vous avez le code source qui compile sur Visual Studio 2010. Je vous laisse le soin de fermer cette issue, ou de la laisser ouverte, mais je ne ferai rien de plus à ce sujet.

Bonne journée.

**Comment by sixcentgeorge** [comment]
je prefere la laisser ouverte..
AU CAS OU , SI JAMAIS LE CODE REDEVENAIT IMCOMPILABLE.. Y S ADRESSERONT A MOI PAR PM.. LES INCONNUS ET NOUVEAUX BIENVENUS , OU DIRECTE DANS LA TOPIC.. CA gene personne et ca prend pas PLUS DE PLACE

**Comment by malortie** [comment]
@sixcentgeorge 

> je prefere la laisser ouverte..
AU CAS OU , SI JAMAIS LE CODE REDEVENAIT IMCOMPILABLE..

Si vous rencontrez des problèmes lors de la compilation, vous n'aurez qu'à faire
les recherches pour comprendre leur(s) cause(s).

> Y S ADRESSERONT A MOI PAR PM.. LES INCONNUS ET NOUVEAUX BIENVENUS , OU DIRECTE **DANS LA TOPIC**..

Vous gérerez le code source, les issues en lien avec le code source de
votre mod sur votre propre repository. Ce ne sera pas ici. Précision:
Je ne créérai pas et je ne gèrerai pas le code source de votre mod.

Si vous ne savez pas comment créer un repository, voici comment faire:
https://help.github.com/en/github/getting-started-with-github/create-a-repo

Vous devrez apprendre Git (avec ligne de commande) ou si vous ne voulez
pas utiliser la ligne de commande, vous pouvez utiliser Github Windows,
qui simplifie l'utilisation de Git à l'aide d'une inferface utilisateur.

Je ferme cet issue, car [ce que vous demandiez](https://github.com/malortie/uncompleted-compilable-hl-opfor/issues/6#issue-565824170) a été [réglé](https://github.com/malortie/uncompleted-compilable-hl-opfor/issues/6#issuecomment-587009389) - vous avez
maintenant une version du code source de ce repository qui compile sous
Visual Studio 2010.
